### ISSUE TITLE
request a license

### ISSUE THREAD

**Issue by songsammy** [BenjaminWFox/horizons-js13k2021#2]
For any open source project, license is a must. I'd like to use this project and I want to be sure that I am allowed to do so, like publishing a modified version.  
You may refer to https://choosealicense.com/

**Comment by BenjaminWFox** [comment]
Added in https://github.com/BenjaminWFox/frontiers-js13k2021/pull/3

Have fun, if you end up publishing a modified version I'd love to hear about it!
